package pe.com.sgresan.entidad;
// Generated 07/06/2015 10:37:49 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TCaja generated by hbm2java
 */
public class Caja  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCaja;
     private Date hora;
     private String descripcion;
     private Double entrada;
     private Double salida;
     private Double saldo;
     private Double arqueo;
     private String moneda;
     private String recep;

    public Caja() {
    }
    
    

	public Caja(Integer idCaja, Date hora, String descripcion, Double entrada, Double salida, Double saldo,
			Double arqueo, String moneda, String recep) {
		super();
		this.idCaja = idCaja;
		this.hora = hora;
		this.descripcion = descripcion;
		this.entrada = entrada;
		this.salida = salida;
		this.saldo = saldo;
		this.arqueo = arqueo;
		this.moneda = moneda;
		this.recep = recep;
	}



	public Integer getIdCaja() {
		return idCaja;
	}

	public void setIdCaja(Integer idCaja) {
		this.idCaja = idCaja;
	}

	public Date getHora() {
		return hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public String getDescripcion() {
		return descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Double getEntrada() {
		return entrada;
	}

	public void setEntrada(Double entrada) {
		this.entrada = entrada;
	}

	public Double getSalida() {
		return salida;
	}

	public void setSalida(Double salida) {
		this.salida = salida;
	}

	public Double getSaldo() {
		return saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	public Double getArqueo() {
		return arqueo;
	}

	public void setArqueo(Double arqueo) {
		this.arqueo = arqueo;
	}

	public String getMoneda() {
		return moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getRecep() {
		return recep;
	}

	public void setRecep(String recep) {
		this.recep = recep;
	}

   



}


